/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BSidebar: typeof import('bootstrap-vue-next')['BSidebar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MobileMenu: typeof import('./src/components/MobileMenu.vue')['default']
    NotificationLayout: typeof import('./src/components/NotificationLayout.vue')['default']
    ProductsSearch: typeof import('./src/components/ProductsSearch.vue')['default']
    ProductsTable: typeof import('./src/components/ProductsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
